name = "VintageRemix"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27f31fe43efe5ddc44a3de4fa1d909849754cacfd0ec28d36c1f98e6e44b3ff7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "1.2.0-pre4"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
