name = "VintageRemix"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55d4a324ade660c66cd37dad4953d01e0bceb53dded3646c939e53c6cc5ed43c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "1.2.0-pre4"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
