name = "VintageRemix"
author = "unilock"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49375ebf93d210071dee17696b2470da3ec9584f5be6945754ea008709e5c99d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
unsup = "1.2.0-pre4"

[options]
acceptable-game-versions = ["1.12", "1.12.1", "1.12.2"]
